# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run lint

  Test:
    runs-on: ubuntu-latest
    needs: [Lint]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run test

  SitRep:
    needs: [Lint, Test]
    environment: sitrep-env
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run sitrep
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        USERNAME: ${{ secrets.USERNAME }}

